// <auto-generated />
namespace CSharpBootCamp.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_added_customer_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_added_customer_status));
        
        string IMigrationMetadata.Id
        {
            get { return "202412090927164_mig_added_customer_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
